### ISSUE TITLE
HashMap is not properly serialized to a JS object.

### ISSUE THREAD

**Issue by ccarral** [cloudflare/serde-wasm-bindgen#10]
I don't know if this feature was meant to be suported, but I noticed that a rust struct that contains 
a HashMap doesn't get serialized to a
```json
 {"key":"value"}
```
object but maps the HashMap to an empty object instead.

Example:
```rust

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SomeStruct {
    pub name: String,
    pub data: HashMap<String, String>,
}

fn test_serialize() {
    let name = "Foo".to_string();
    let mut data = HashMap::<String, String>::new();
    data.insert("professor".to_string(), "Stephen Hawking".to_string());
    let rust_struct = SomeStruct { name, data };

    let serialized_1 = serde_wasm_bindgen::to_value(&rust_struct).unwrap();

    let serialized_2 = JsValue::from_serde(&rust_struct).unwrap();

    log!("{:?}", serialized_1); // Output: JsValue(Object({"name":"Foo","data":{}}))
    log!("{:?}", serialized_2); // Output: JsValue(Object({"name":"Foo","data":{"professor":"Stephen Hawking"}}))

}
```

**Comment by asaaki** [comment]
I was also bitten by this behaviour.
According to the comment at

https://github.com/cloudflare/serde-wasm-bindgen/blob/e0d23123ca79132a5f792052799a35978805ce99/src/ser.rs#L369-L376

we might need to wait.
Until then I still have to resort to plain `JsValue::from_serde` instead.

**Comment by RReverser** [comment]
JS `Map` is the closest to Rust `HashMap`, since both allow arbitrary keys and values. If you want to allow serialization of string-keyed `HashMap`s to JS objects, please send a PR that adds a corresponding config.

**Comment by mischnic** [comment]
This seems to be the only format difference between this crate and [napi-rs](https://github.com/napi-rs/napi-rs)'s serde functionality.

>  please send a PR that adds a corresponding config

What would that config look like? Something similar to `#[serde(with = "serde_bytes")]` (I don't even know if that is possible)?

**Comment by RReverser** [comment]
> What would that config look like? Something similar to `#[serde(with = "serde_bytes")]` (I don't even know if that is possible)?

Yeah I don't think that's possible, serde_bytes trick works because it invokes corresponding `serialize_bytes` / `deserialize_bytes` Serde methods while not caring about what a specific encoder will do there.

What I had in mind is instead option on [Serializer](https://docs.rs/serde-wasm-bindgen/0.2.0/serde_wasm_bindgen/struct.Serializer.html) itself, so you could construct a custom instance like `let serializer = Serializer::new().serialize_maps_as_objects(true);` and use that instance for such cases.

**Comment by RReverser** [comment]
> object but maps the HashMap to an empty object instead.

I probably should also note here: it's _not_ an empty object. Rust `Debug` representation just can't handle the JS `Map` instance in this case and doesn't print its entries, but they're still there and are accessible from JavaScript.

**Comment by mischnic** [comment]
Thank you for the quick response!

**Comment by mschoenebeck** [comment]
How is this solved? Keys still don't show up in my map. They seem to be there, as noted by @RReverser but `Object.keys(map)` still returns an empty array when logging in JS console.

So how can I retrieve the keys of the returned HashMap object? The workaround mentioned using `JsValue::from_serde(&map)` doesn't work either since this function seems to be removed from current version.

**Comment by RReverser** [comment]
> How is this solved?

You can see above that this was solved via #12, from there you can see the new option serialize_maps_as_objects which is documented in README too.

**Comment by mschoenebeck** [comment]
Sorry, I don't understand how to enable that option using the #derive macros. Are there any examples for that?

**Comment by RReverser** [comment]
Yeah, `#[derive(...)]` itself in Serde is generic over arbitrary (de)serializers, it doesn't know what the output format is and can't control serializer options - those always need to be specified by the user.

**Comment by RReverser** [comment]
Couple of notes about your snippet:

1. `T: Serialize` should be enough for bounds.
2. You can rename it to just `serialize` or `to_value`, it's not specific to hashmaps.
3. Best not to use `.unwrap()`, but properly handle/propagate error via `Result`.

**Comment by mschoenebeck** [comment]
Thanks for the advice! I updated the snippet.

**Comment by RReverser** [comment]
> How is this solved? Keys still don't show up in my map. They seem to be there, as noted by @RReverser but `Object.keys(map)` still returns an empty array when logging in JS console.

Btw unless you really need those to be JS objects, you can get Map keys via `Array.from(map.keys())` or just by iterating over the map.
