### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by trevyn** [cloudflare/serde-wasm-bindgen#19]
Not sure quite what the required level of madness would be, but it would be hot to be able to write something like:

```rust
#[serde_wasm_bindgen]
pub fn pass_value_to_js() -> Result<MyRustStruct, JsValue> {
    // ...
}
```

that gets expanded to

```rust
#[wasm_bindgen]
pub fn pass_value_to_js() -> Result<JsValue, JsValue> {
    serde_wasm_bindgen::to_value(
        // ...
    ) // plus a type guard
}
```

PLUS a TypeScript `.d.ts` definition file...

**Comment by RReverser** [comment]
Yeah me neither. Due to complexity seems rather out of scope of this project tbh, but if someone would make a macro like this, it sure could be cool.

**Comment by trevyn** [comment]
So `wasm-bindgen` does some [truly bonkers stuff](https://rustwasm.github.io/docs/wasm-bindgen/contributing/design/describe.html) to generate its TypeScript definitions, which initially scared me.

But I'm most interested in the case of relatively simple, flat user-defined structs that only contain basic types. If the macro is invoked on both the struct and the function, it should have all the info it needs to do a basic typedef without getting too crazy in the type system. Then more generality could be future work.

Totally cool if you consider this out-of-scope; it should be easy to layer on top of `serde-wasm-bindgen` as a separate crate. I suspect I'll give this first-pass version a shot, and will link back to this issue to keep everyone updated. :)

**Comment by RReverser** [comment]
You might be interested in looking at https://crates.io/crates/typescript-definitions - I remember seeing it briefly while searching for some other stuff in the past, but never dug in. However, given that both that crate and serde-wasm-bindgen build upon Serde attributes, it's possible combining the two on same types might work out of the box, or at least with little effort.

But yeah, I think an adapter that combines the two (if such is necessary) would be a bit out of scope of implementation. That said, I'm happy to add links or section to the docs showing how to use them together once you figure it out :)

Closing this issue for now.
