### ISSUE TITLE
`#serde(default)`

### ISSUE THREAD

**Issue by fosskers** [cloudflare/serde-wasm-bindgen#20]
After some strange results downstream, I discovered that `#serde(default)` doesn't work. Here are some tests to demonstrate the issue:

```rust
#[derive(Deserialize)]
struct Person0 {
    name: String,
    things: Option<Vec<u32>>,
}

#[derive(Deserialize)]
struct Person1 {
    name: String,
    #[serde(default)]
    things: Vec<u32>,
}

#[wasm_bindgen_test]
fn serde_default() {
    let text = "{\"name\": \"Jack\"}";
    let js = JSON::parse(text).unwrap();

    assert!(from_value::<Person0>(js.clone()).is_ok());
    assert!(from_value::<Person1>(js).is_ok());
}
```
We would expect both `Person0` and `Person1` to deserialize from the same source `String`, but `Person1` fails with a very strange message that `Reflect.get called on a non-object`. 

Now I see that PR #14 exists... would it fix this issue?

**Comment by RReverser** [comment]
> Now I see that PR #14 exists... would it fix this issue?

I don't know. As mentioned in comments, in its current state it breaks some other things and I'm not sure if author is interested in reworking it.

If you want to implement this in a non-breaking way, I'd be happy to review your PR.

**Comment by RReverser** [comment]
Or, you can try it out yourself and see if both `Option` and `serde(default)` still work.

**Comment by fosskers** [comment]
Hot damn, thank you very much.
