### ISSUE TITLE
Suspected low-level issue with `HashMap` -> JS `Map` Conversion

### ISSUE THREAD

**Issue by fosskers** [cloudflare/serde-wasm-bindgen#23]
I have stumbled upon a tricky bug that manifests itself differently in different browsers.

To the point, there may be an issue with encoding Rust `HashMap`s as Javascript `Map` values (as `serde-wasm-bindgen` seems to be doing). Without having looked at how it does that, I've boiled the issue down to the following sample. This Rust code:
```rust
#[derive(Debug, Serialize, Deserialize)]
struct Foo {
    foo: HashMap<String, bool>,
}

fn foo() {
    let mut foo = HashMap::new();
    foo.insert("Jack".to_string(), true);
    let thing = Foo { foo };
    let js = swb::to_value(&thing).unwrap();
    let st = js_sys::JSON::stringify(&js).unwrap();
    log!("[Rust] ", thing);
    log!("[swb::to_value] ", js);
    log!("[JSON::stringify] ", st);
    log!("[swb::from_value] ", swb::from_value::<Foo>(js).unwrap());
    let sj = serde_json::to_string(&thing).unwrap();
    log!("[serde_json] ", sj);
    log!("[JSON::parse] ", js_sys::JSON::parse(&sj));
}
```
produces the following console output:
```
"[Rust] " Foo {
    foo: {
        "Jack": true,
    },
}
"[swb::to_value] " JsValue(Object({"foo":{}}))
"[JSON::stringify] " "{\"foo\":{}}"
"[swb::from_value] " Foo {
    foo: {
        "Jack": true,
    },
}
"[serde_json] " "{\"foo\":{\"Jack\":true}}"
"[JSON::parse] " Ok(
    JsValue(Object({"foo":{"Jack":true}})),
)
```
Notice that having ran `to_value`, the internal `Map` either isn't respecting `Debug`, or somehow lost the values. The `stringify` line after that suggests lost values, except that upon decoding (the `from_value`), the `HashMap` has miraculously returned. The last two were sanity checks - `serde_json` chooses to render `HashMap`s into plain `Object`s by default, which also seem to print properly via `Debug`.

Now, this is manifesting an issue in a browser extension I'm building. Data can be transmitted between Extension Components easily via the "ports" API, which blends well with `serde-wasm-bindgen` since it's all `JsValue`s. I've had no issue sending over serialized structs that contain `HashMap` fields until last week, when the struct I tried to send over was initially fetched from an `Arc<Mutex<...>>` wrapping. Since `to_value` only needs `&` this shouldn't be an issue, but when I send the data to the other component... poof, the `HashMap`s deserialize as completely empty. Note that this only occurs in Chrome.

Do you have any idea as why that might be?

For now I'm going to try the `serialize_maps_as_objects(true)` option listed in the README.

**Comment by fosskers** [comment]
I do very much need the non-string key case, so I will keep testing.

**Comment by fosskers** [comment]
I'm still having the issue (on Chrome) when I use the JS `Map` internally (your default). Do you have any idea what could be the root of this?

**Comment by RReverser** [comment]
I can't really help you without specific example of code + data and expected vs actual behaviour. The code above is fine aside from the mentioned `Map` vs plain objects and `Debug` impl issues. Any other code needs to be looked at separately.

To me it still sounds like you _don't_ want `Map`, because those are not `JSON.stringify`-able in JavaScript, and you seem to want JSON, so there is conflict in requirements.

**Comment by fosskers** [comment]
Unfortunately I'm NDA'd and don't have time at the moment to write up a separate reproduction. I'm not actually trying to print anything anywhere in the real code - it's that when I encode a `Arc<Mutex<HashMap>>` into a `JsValue` via `serde-wasm-bindgen`, send it to another browser extension exponent and then decode, the resulting `HashMap` is empty.

**Comment by RReverser** [comment]
Right, but it depends how you send it to another browser extension (exponent? did you mean component?). As I said, if you want to use JSON as an intermediate formal, then it won't work with ES6 Maps, but if you can use simple messaging mechanism like [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) then you can just avoid JSON altogether and send values directly.

This is one of those cases where details matter - without them, I can only suggest to look into provided links and wish good luck. Sorry can't help more.

**Comment by fosskers** [comment]
Yes I am using `postMessage`, but the values needs to be `JsValue` first, right? Meaning a need a medium like `serde-wasm-bindgen` first?

**Comment by fosskers** [comment]
Actually yes, they do need to be `JsValue`, because I'm calling `Function::call1` to make it work.

**Comment by RReverser** [comment]
> Meaning I need a medium like `serde-wasm-bindgen` to put the Rust values through first?

Yeah, you can and need to use serde-wasm-bindgen, just saying you don't need `js_sys::JSON` afterwards.

**Comment by RReverser** [comment]
I'll close this now as it doesn't look like an actual issue.

**Comment by fosskers** [comment]
I did end up working around it.
