### ISSUE TITLE
Deserializing a BigInt inside a tagged enum fails

### ISSUE THREAD

**Issue by LPGhatguy** [cloudflare/serde-wasm-bindgen#30]
I put together a runnable repro here: https://github.com/LPGhatguy/serde-wasm-bindgen-bug-report

Defining an enum like...

```rust
#[derive(Serialize, Deserialize)]
#[serde(tag = "type")]
enum Foo {
    A { value: u64 },
}
```

and trying to deserialize it from a JS object containing a BigInt for the `u64` fails with this error in Chrome:

```
serde_wasm_bindgen_bug.js:364 Uncaught (in promise) Error: invalid type: JsValue(BigInt), expected any value
...
    at Object.give_value (serde_wasm_bindgen_bug.js:201)
    at main (index.js:7)
```

Removing the `#[serde(tag = "type")]` works, changing the BigInt to a regular number works, using a smaller integer type works, and using a struct instead also works. It seems to be a funny intersection of all of these features.

**Comment by RReverser** [comment]
@mfish33 do you want to take a look at this one?
