### ISSUE TITLE
Better interop between Tauri and serde-wasm-bindgen

### ISSUE THREAD

**Issue by JohnScience** [cloudflare/serde-wasm-bindgen#47]
Related issue: https://github.com/tauri-apps/tauri/issues/6455

**Comment by RReverser** [comment]
Sorry, this is not very actionable issue. If there's a bug in serde-wasm-bindgen, please submit it separately with repro steps. If this is a request for some framework-specific functionality, it should go into the framework.

**Comment by JohnScience** [comment]
@RReverser It concerns `serde-wasm-bindgen` because there's another way how the data is converted between Rust and JavaScript. And this at least should be mentioned in the documentation of `serde-wasm-bindgen`, if not properly supported.
