### ISSUE TITLE
Hitting an unreachable! panic in serializing

### ISSUE THREAD

**Issue by stevenroose** [cloudflare/serde-wasm-bindgen#52]
We're hitting an unreachable! panic inside the call to `serde_wasm_bindgen::to_value`. I've been tracking down the serialization code for the type we're serializing and can't find any unreachable! statement anywhere.

Also can't find an unreachable! statement inside this crate, but maybe there is something in dependent crates?

Did anyone every encounter an unreachable! panic while serializing to JsValue?

**Comment by RReverser** [comment]
Are you sure you're encountering `unreachable!` (Rust macro) and not `unreachable` (Wasm instruction)? The latter is just a representation of any trap in Wasm, which in Rust case would be any kind of panic.

If it is the latter, then make sure to include something like https://github.com/rustwasm/console_error_panic_hook in your project which should print the panic message before trapping.

**Comment by stevenroose** [comment]
Ooooh, that is super helpful information. Yeah it was an `unreachable` wasm instruction. Thanks!

**Comment by RReverser** [comment]
No problem. I'll close this for now, but if you find that the panic was indeed a bug in this library, please feel free to open a new issue with repro details.

**Comment by stevenroose** [comment]
Update: managed to use that tool and get the panic message. Fwiw, it had to do with some encoding thing where BE was converted to LE (u64) so a small integer overflowed the JS number space of 53 bits..

**Comment by RReverser** [comment]
Hmm weird. We have specific checks for that scenario so it should be returned as a gracefully-handled `Result` instead of panicking. https://github.com/cloudflare/serde-wasm-bindgen/blob/620cb3d3c36e59479753949b05aa93c29554cc3c/src/ser.rs#L343

If you can reproduce with a minimal example, please raise an issue.

Or are you saying it was a panic outside this crate?
