### ISSUE TITLE
Structures containing usize seems to create BigInt dependency in generated JavaScript bindings

### ISSUE THREAD

**Issue by nwoods-cimpress** [cloudflare/serde-wasm-bindgen#53]
### Describe the Bug

For some reason, having a `usize` in a structure seems to result in bindings that have a dependency on `BigInt`, but using `u32` instead of the `usize` does not trigger the same dependency.  Because `usize` is the same thing as `u32` on JavaScript platforms, I would expect these to create identical results.

### Steps to Reproduce

1. Unpack `wasm-bindgen-bigint-issue.zip` ([wasm-bindgen-bigint-issue.zip](https://github.com/rustwasm/wasm-bindgen/files/12407820/wasm-bindgen-bigint-issue.zip))
2. `wasm-pack build --target nodejs`
3. Scrutinize the generated `wasm_bindgen_bigint_issue.js`
4. In `src/lib.rs`, change `pub val: usize` to `pub val: u32`
5. `wasm-pack build --target nodejs`
6. Scrutinize the generated `wasm_bindgen_bigint_issue.js`

### Expected Behavior

I would expect the `wasm_bindgen_bigint_issue.js` generated by steps 3 and 6 to be identical.

### Actual Behavior

The two files are not identical; there are two snippets present when `val` is a `usize`:

````
module.exports.__wbindgen_bigint_from_u64 = function(arg0) {
    const ret = BigInt.asUintN(64, arg0);
    return addHeapObject(ret);
};
````

````
module.exports.__wbindgen_error_new = function(arg0, arg1) {
    const ret = new Error(getStringFromWasm0(arg0, arg1));
    return addHeapObject(ret);
};
`````

I first reported this to the `wasm-bindgen` people but they identified it as pertaining to this project (https://github.com/rustwasm/wasm-bindgen/issues/3564)

**Comment by RReverser** [comment]
Problem is that Serde doesn't differentiate between `usize` and other types - it always invokes `serialize_u64` method on the serializer, so we have no way of knowing what was actually there.

Aside from that, I'd also note that in

> Because `usize` is the same thing as `u32` on JavaScript platforms, I would expect these to create identical results.

you probably mean that it's the same thing on `wasm32-unknown-unknown`. However, this is not a future-proof assumption as `wasm64-*` targets are being actively developed and already supported by couple of compilers. In those, pointers and `usize` will have 64 bit size correspondingly.

There are two options here if you really want to encode `usize` as `u32`: 1) change the type of the field in structures or 2) use Serde's [`serialize_with`/`deserialize_with`/`with` attributes](https://serde.rs/field-attrs.html) to cast it during serialization only.

**Comment by nwoods-cimpress** [comment]
You're absolutely correct; I was assuming `wasm32-unknown-unknown`, and yes I do understand that 64-bit WebAssembly is in the future, but I suppose that I'm looking at the generated JavaScript bindings and at some level whatever it is generating must be aware of the size of pointers on the platform.  For example I see this in my generated JavaScript bindings:

````
module.exports.greet = function() {
    try {
        const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
        wasm.greet(retptr);
        var r0 = getInt32Memory0()[retptr / 4 + 0];
        var r1 = getInt32Memory0()[retptr / 4 + 1];
        var r2 = getInt32Memory0()[retptr / 4 + 2];
        if (r2) {
            throw takeObject(r1);
        }
        return takeObject(r0);
    } finally {
        wasm.__wbindgen_add_to_stack_pointer(16);
    }
};
````

I'd assume that on `wasm64-unknown-unknown`, we'd see things like `var r1 = getInt64Memory0()[retptr / 8 + 1];`

> Problem is that Serde doesn't differentiate between `usize` and other types - it always invokes `serialize_u64` method on the serializer, so we have no way of knowing what was actually there.

I really don't understand the interactions between the `wasm-bindgen`, `serde` and `serde-wasm-bindgen` layer cake, but would it be fair to say that if `serde` was changed to call `serialize_u32`, this problem would go away?

**Comment by RReverser** [comment]
> but would it be fair to say that if `serde` was changed to call `serialize_u32`, this problem would go away?

Yeah. I think you should be able to do something like

```rust
fn serialize_usize_as_u32<S: Serializer>(value: &usize, ser: S) -> Result<S::Ok, S::Error> {
  ser.serialize_u32(*value as _)
}

#[derive(Serialize)]
struct YourStruct {
  #[serde(serialize_with = "serialize_usize_as_u32")]
  your_field: usize,
}
```

See the linked page about field attributes for more details or just google examples of `serialize_with` / `deserialize_with` to figure out function signatures.

**Comment by RReverser** [comment]
Closing as it seems the question was answered?
