### ISSUE TITLE
json_compatible Deserializer

### ISSUE THREAD

**Issue by hamza1311** [cloudflare/serde-wasm-bindgen#54]
[`serde_wasm_bindgen::Serializer::json_compatible`](https://docs.rs/serde-wasm-bindgen/latest/serde_wasm_bindgen/struct.Serializer.html#method.json_compatible) exists but there is no equivalent for `Deserializer`.

```rust
let date = js_sys::Date::new_0();
let object = js_sys::Object::new();
js_sys::Reflect::set(&object, &"date".into(), &date).unwrap();
gloo::console::log!(&object);
let value: serde_json::Value = serde_wasm_bindgen::from_value(object.into()).unwrap();
gloo::console::log!(format!("{value:?}"));
```

This logs:
![image](https://github.com/cloudflare/serde-wasm-bindgen/assets/47357913/971abaa8-a08a-494f-87d4-ecb88eff39a6)

I would like there to be a way to deserialize a date somehow.

**Comment by RReverser** [comment]
Well you can't deserialize a date from JSON into a `Date` object because JSON doesn't know anything about those higher-level types, so the deserializer is still compatible.
