### ISSUE TITLE
IntoWasmAbi

### ISSUE THREAD

**Issue by smessmer** [cloudflare/serde-wasm-bindgen#56]
Is it possible to implement `IntoWasmAbi` for a type that supports `Serialize` via `serde-wasm-bindgen`? Passing them directly instead of passing `JsValue` would make it more type-safe to pass those objects into JavaScript using `#[wasm_bindgen]` interfaces.

**Comment by RReverser** [comment]
No, because for ABI you need to have control over both Rust and JS parts which only wasm-bindgen itself has. That said, using `#[wasm_bindgen]` should be perfectly type-safe, especially when combined with something like [tsify](https://lib.rs/crates/tsify).

**Comment by RReverser** [comment]
Correction: looks like `tsify` - which integrated with `serde-wasm-bindgen` - has attribute to derive `IntoWasmAbi` nowadays, so yes, it's possible, but you'll need to consult that library.

**Comment by louneskmt** [comment]
As `tsify` seems unmaintained, what about implementing this in this library? Is there any rationale to not support something like this? Would you accept a PR?
