### ISSUE TITLE
Return as Result<JsValue, JsValue>

### ISSUE THREAD

**Issue by dakom** [cloudflare/serde-wasm-bindgen#6]
The docs say that a function can pass a value to javascript by returning as `Result<JsValue, JsValue>`, however the error type is `serde_wasm_bindgen::Error`

This can be worked around via `map_err(|err| err.into())` but would be nice to have it be `JsValue`

**Comment by RReverser** [comment]
Unfortunately, this isn't possible, because `serde` requires error type to implement `serde::de::Error`. Since `JsValue`, `serde` and `serde-wasm-bindgen` all live in different crates, we have to use a wrapper type here to implement that trait.

**Comment by RReverser** [comment]
Just to note: another way this should work is if you use `?` operator, which performs `err.into()` under the hood.
