### ISSUE TITLE
serialization produces `Map` object for structs with "flatten"

### ISSUE THREAD

**Issue by Niedzwiedzw** [cloudflare/serde-wasm-bindgen#9]
example: 

```rust
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ResultStatistics {
    #[serde(flatten)]
    pub basic: ConstraintConfig,
    pub total_price: f64,
    pub total_cpp: f64,
}
```

produces ES Map object on the wasm side.

**Comment by RReverser** [comment]
This is an unfortunate limitation of Serde itself, see https://github.com/serde-rs/serde/issues/1346. Unfortunately, I don't think we can do anything on serde-wasm-bindgen side here.
